---
title: "NY NOAA Analysis"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
runtime: shiny
---

```{r}
library(flexdashboard)
library(forcats)
library(tidyverse)
library(dplyr)
library(readr)
library(plotly)
library(janitor)
library(shiny)
library(stringr)
library(rsconnect)

ny_noaa = read_csv("../data/nynoaadat.zip") %>%
  clean_names %>%
  separate(date, into = c("year", "month","day"), sep = "-") %>%
  filter(year >= 2000)

ny_noaa_plot_1 = ny_noaa %>%
  drop_na(prcp) %>%
  arrange(year, month, day) %>%
  select(id, year, month, day, prcp) %>%
  mutate(year = as.factor(year), date = str_c(month, day, sep = ".")) %>%
  select(-month, -day) %>%
  group_by(year, date) %>%
  mutate(prcp = mean(prcp)) %>%
  ungroup()



#PLOT 1
which_year = ny_noaa_plot_1 %>% distinct(year) %>% pull()


# selectInput widget
selectInput("year_choice", label = h3("Select year"),
            choices = which_year, selected = "2010")

renderPlotly({
    ny_noaa_plot_1 %>%
    filter(year == input$year_choice) %>%
    plot_ly(x = ~date, y = ~prcp, type = "scatter", mode = "lines",
          alpha = 0.5,
          color = ~prcp) %>%
    layout(title = "Precipitation Trend Through the Year")
})

```


### Chart B

```{r}
#PLOT 3
ny_noaa_plot_3 = ny_noaa %>%
  mutate(year = as.numeric(year), tmax = as.numeric(tmax)) %>%
  drop_na(tmax) %>%
  select(year, month, day, tmax) %>%
  group_by(year, month) %>%
  summarize(tmax = mean(tmax)) %>%
  ungroup()

max_year = 2010
min_year = 2000

# sliderInput widget
sliderInput("year_range", label = h3("Choose year range"), min = min_year,
        max = max_year, value = c(2000, 2010))


renderPlotly({
    ny_noaa_plot_3 %>%
    filter(year %in% input$year_range[1]:input$year_range[2]) %>%
    plot_ly(x = ~month, y = ~tmax, type = "scatter",
          alpha = 0.0001,
          color = ~year) %>%
    layout(title = "Maximum Temperature Through the Year")
})
```

### Chart C

```{r}


```



